### PR TITLE
add official 1.20.6 support

### PR DESCRIPTION
**Pull request by NonSwag**
## Description

This PR adds official support for 1.20.6
- cloud command framework was updated to utilize the latest addition of paper brigadier
- removed dead versions from "supported" list

## Checklist

- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code

### CODE REVIEW

**Review by TheMeinerLP — APPROVED** [review]
LGTM, tested locally. Only a generic fawe bug is present but thats fine

**Comment by NonSwag** [comment]
what do you mean by generic fawe bug ?

**Comment by TheMeinerLP** [comment]
image
Ref: https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/2752
Ref2: https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2742

**Comment by NonSwag** [comment]
oh thats unrelated then

**Comment by TheMeinerLP** [comment]
Not really, we use that API to create our config

**Pull request merged**
